services:
  app:
    build: .
    ports:
      - "8080:5000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - idtech-redis-data:/data

volumes:
  idtech-redis-data:
